# -*- coding: utf-8 -*-
"""analise de sentimentos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y5wE-FMXqmkzQqz8e7wL88Y_GRFM1rwH
"""

# !pip install googletrans==3.1.0a0

import nltk
nltk.download('vader_lexicon')

from nltk.sentiment.vader import SentimentIntensityAnalyzer
from googletrans import Translator

texto = str(input("digite: "))
traduzir = Translator()

a = traduzir.translate(texto, dest="en").text
print(a)
b = traduzir.translate(a, dest="pt").text
print(b)
s = SentimentIntensityAnalyzer()

score = s.polarity_scores(a)

print(score)
if(score['compound'] > 0):
  print('positivo')
elif(score['compound'] < 0):
  print('negativo')
else:
  print('neutro')

