# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bk7_lnr8DrKp6INzsKpnbz-xXBrbsG9r
"""

import streamlit as st
import nltk 

print('analise de satisfaçao do cliente')
user_input = str(input('por favor, avalie o nosso atendimento:  '))

from nltk.sentiment.vader import SentimentIntensityAnalyzer
#nltk.download('vader_lexicon')
s = SentimentIntensityAnalyzer()

score = s.polarity_scores(user_input)

if(score == 0):
    print('jg')
elif (score['neg'] != 0):
     print('analise negativa')
elif (score['pos'] != 0):
     print('analise positivo')